#!/usr/bin/env python
from __future__ import print_function, unicode_literals

from PyInquirer import style_from_dict, Token, prompt, Separator
from pprint import pprint
import sys
from pyfiglet import Figlet
import argparse
f = Figlet(font='big')
print(f.renderText('DeepLI'))


sys.argv

style = style_from_dict({
    Token.Separator: '#cc5454',
    Token.QuestionMark: '#673ab7 bold',
    Token.Selected: '#cc5454',  # default
    Token.Pointer: '#673ab7 bold',
    Token.Instruction: '',  # default
    Token.Answer: '#f44336 bold',
    Token.Question: '',
})

x = "xxxxx"
questions = [
{
'type': 'input',
'name': 'first_name',
'message': 'try  '+x,
}
]


answers = prompt(questions,style=style)
print(str(sys.argv),answers)
